---
name: Documentation Request
description: Suggest an idea to add documentations
title: '[Docs]: '
labels: ['documentation']
assignees:
  - Seyrinian
body:
  - type: dropdown
    id: project
    attributes:
      label: What project is concerned by this documentation?
      multiple: true
      options:
        - boilerplate-nuxt
        - boilerplate-vue
        - tools
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the documentation you're interested in.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
